name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'PRD' || 'DEV' }}
    steps:
      - uses: actions/checkout@v3

      - name: Set Vercel Token and Environment
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN_PRD }}" >> $GITHUB_ENV
            echo "VERCEL_ENV=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN_DEV }}" >> $GITHUB_ENV
            echo "VERCEL_ENV=preview" >> $GITHUB_ENV
          fi

      - name: Debug Vercel Token
        run: echo 'Vercel Token Length: ${#VERCEL_TOKEN}'
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Authenticate with Vercel
        run: |
          if [[ -z "$VERCEL_TOKEN" ]]; then
            echo "Error: VERCEL_TOKEN is not set"
            exit 1
          fi
          vercel login --token=$VERCEL_TOKEN

      - name: Pull Vercel Environment Variables
        run: vercel pull --yes --environment=$VERCEL_ENV --token=$VERCEL_TOKEN

      - name: Install Dependencies and Build Project
        run: npm install && npm run build

      - name: Deploy Project to Vercel
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            vercel deploy --prebuilt --token=$VERCEL_TOKEN
          fi