name: Vercel Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Deploy to Vercel Dev
        if: github.ref == 'refs/heads/dev'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_DEV }}
        run: vercel deploy --env VERCEL_ENV=dev
      - name: Deploy to Vercel Prd
        if: github.ref == 'refs/heads/main'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_PRD }}
        run: vercel deploy --env VERCEL_ENV=prd